"""
Daily briefing API — stored briefings generated by the cron job plus
on-demand regeneration with user-specified filters.
"""

import logging
from datetime import date, timedelta

import anthropic
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.database import get_db
from app.models import DailyBriefing
from app.routers.chat import _build_context

log = logging.getLogger(__name__)
router = APIRouter()

BRIEFING_SYSTEM = """You are an epidemiological intelligence analyst for Biothreat Radar, a multi-stream global biosurveillance platform.

Your context contains structured pipeline data AND either live web-search results or supplemental model knowledge. Use all of it.

Write a daily intelligence briefing for public health professionals and decision-makers:
- Lead with the most actionable or notable signal — draw from whichever source has the strongest content
- Structure: key signal → notable findings by stream → global context → data gaps / caveats
- Cite numbers precisely when available from structured data
- When drawing on web-search results, treat them as you would a news item: quote the headline or key fact
- When the context includes "[Model knowledge]" sections, use them for background but label them clearly
- 3–4 paragraphs, approximately 350–450 words
- Professional and direct — no filler phrases, no unnecessary hedging
- Never treat zero pipeline rows as confirmation of quiescence; call out missing streams explicitly"""


def _filter_prompt(filters: dict | None) -> str:
    if not filters:
        return "Provide a comprehensive overview across all active surveillance streams."
    parts = []
    pathogens = filters.get("pathogens", [])
    if pathogens:
        parts.append(f"Focus specifically on: {', '.join(pathogens)}. Briefly note other signals only if exceptional.")
    streams = filters.get("streams", [])
    if streams:
        parts.append(f"Prioritize data from these streams: {', '.join(streams)}.")
    region = filters.get("region")
    if region == "us":
        parts.append("Restrict analysis to US domestic signals (NWSS, TGS). Note global context only if directly relevant.")
    return " ".join(parts) if parts else "Provide a comprehensive overview across all active surveillance streams."


async def generate_briefing_text(
    context: str,
    filters: dict | None = None,
    today: date | None = None,
) -> str:
    """Call Anthropic API and return the briefing text."""
    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
    focus = _filter_prompt(filters)
    today_str = (today or date.today()).isoformat()

    response = await client.messages.create(
        model="claude-sonnet-5",
        max_tokens=1200,
        system=BRIEFING_SYSTEM,
        messages=[{
            "role": "user",
            "content": (
                f"Today is {today_str}. {focus}\n\n"
                "Generate the daily biosurveillance briefing using the data below.\n\n"
                + context
            ),
        }],
    )
    return response.content[0].text


@router.get("/latest")
async def get_latest_briefing(db: AsyncSession = Depends(get_db)):
    """Return the most recent stored daily briefing."""
    result = await db.execute(
        select(DailyBriefing)
        .order_by(desc(DailyBriefing.generated_at))
        .limit(1)
    )
    briefing = result.scalar_one_or_none()

    if not briefing:
        return {"briefing": None, "generated_at": None, "briefing_date": None}

    return {
        "briefing": briefing.content,
        "generated_at": briefing.generated_at.isoformat(),
        "briefing_date": briefing.briefing_date.isoformat(),
        "filters": briefing.filters_json,
        "is_default": briefing.is_default,
        "model": briefing.model_id,
    }


class GenerateRequest(BaseModel):
    filters: dict | None = None  # {"pathogens": [...], "streams": [...], "region": "us"|"global"}


@router.post("/generate")
async def generate_briefing(body: GenerateRequest, db: AsyncSession = Depends(get_db)):
    """Generate a new briefing (optionally filtered) and store it."""
    if not settings.anthropic_api_key:
        return {"error": "ANTHROPIC_API_KEY not configured on this server."}

    try:
        context = await _build_context(db)
        content = await generate_briefing_text(context, body.filters)
    except Exception as e:
        log.exception("Briefing generation failed")
        return {"error": str(e)}

    today = date.today()
    db_row = DailyBriefing(
        briefing_date=today,
        content=content,
        data_context=context,
        filters_json=body.filters,
        model_id="claude-sonnet-5",
        is_default=(body.filters is None),
    )
    db.add(db_row)
    await db.commit()
    await db.refresh(db_row)

    return {
        "briefing": content,
        "generated_at": db_row.generated_at.isoformat(),
        "briefing_date": today.isoformat(),
        "filters": body.filters,
        "is_default": db_row.is_default,
    }
